clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  gcc:
    image: gcc
    secrets:
      - source: aaa
        target: abc
    commands:
      - echo Starting compile.
      - gcc -Wall -o shift shift.c
      - ./shift
      - echo $AAA
      - echo $ABC
      - echo $PATH
