clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  compile:
    image: gcc
    secrets:
      - source: aaa
        target: abc
    commands:
      - echo Starting compile.
      - gcc -Wall -o shift shift.c
      - ./shift
      - echo $AAA
      - echo $ABC
      - echo $PATH

  ssh:
    image: appleboy/drone-ssh
    host: bluebobo.no-ip.org
    port: 9282
    username: pi
    password: 11111111
    script:
      - echo This is ARCH PI
      - touch a.txt
      - ls -al
    when:
      branch: [ master, develop]
      event: pull
