clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  gcc:
    image: gcc
    environment:
    commands:
      - echo Starting compile.
      - gcc -Wall -o shift shift.c
      - ./shift
      - echo $STRING
      - echo $PATH
