clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  compile:
    image: gcc
    secrets:
      - source: aaa
        target: abc
    commands:
      - echo Starting compile.
      - gcc -Wall -o shift shift.c
      - ./shift
      - echo $AAA
      - echo $ABC
      - echo $PATH

  master:
    image: gcc
    commands:
      - echo master
    when:
      branch: master

  develop:
    image: gcc
    commands:
      - echo develop
    when:
      branch: develop

  push:
    image: gcc
    commands:
      - echo push
    when:
      event: push

  ssh:
    image: appleboy/drone-ssh
    host: bluebobo.no-ip.org
    port: 9282
    username: pi
    secrets:
      - source: key
      - target: ssh_key
    script:
      - echo This is ARCH PI
      - touch a.txt
      - ls -al
